# Generated by Django 3.1.2 on 2021-04-16 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_kw_extractor', '0002_uploadpdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugdments',
            name='orgao',
            field=models.TextField(default='Superior Tribunal de Justiça'),
        ),
        migrations.AddField(
            model_name='jugdments',
            name='processo',
            field=models.TextField(default='--'),
        ),
        migrations.AddField(
            model_name='jugdments',
            name='texto',
            field=models.TextField(default="something's wrong"),
        ),
    ]
