# Generated by Django 3.1.2 on 2021-04-23 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_kw_extractor', '0003_auto_20210416_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugdments',
            name='ementa',
            field=models.TextField(default='ementa'),
        ),
    ]
