# Generated by Django 3.1.2 on 2021-05-05 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_kw_extractor', '0005_auto_20210505_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='KeywordCount',
        ),
    ]
