# Generated by Django 3.1.2 on 2021-05-26 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_kw_extractor', '0006_auto_20210505_1528'),
    ]

    operations = [
        migrations.CreateModel(
            name='Label_1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_1', models.TextField()),
                ('judgment', models.ForeignKey(default='IRPJ', on_delete=django.db.models.deletion.CASCADE, to='pdf_kw_extractor.jugdments')),
            ],
        ),
        migrations.CreateModel(
            name='Label_2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_2', models.TextField()),
                ('label_1', models.ForeignKey(default='Lucro Real', on_delete=django.db.models.deletion.CASCADE, to='pdf_kw_extractor.label_1')),
            ],
        ),
        migrations.CreateModel(
            name='Label_3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_3', models.TextField()),
                ('label_2', models.ForeignKey(default='Rendimento interno', on_delete=django.db.models.deletion.CASCADE, to='pdf_kw_extractor.label_2')),
            ],
        ),
    ]
