# Generated by Django 3.1.2 on 2021-05-28 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_kw_extractor', '0007_label_1_label_2_label_3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='label_2',
            name='label_1',
        ),
        migrations.RemoveField(
            model_name='label_3',
            name='label_2',
        ),
        migrations.AddField(
            model_name='jugdments',
            name='label_1',
            field=models.TextField(default='IRPJ'),
        ),
        migrations.AddField(
            model_name='jugdments',
            name='label_2',
            field=models.TextField(default='Lucro Real'),
        ),
        migrations.AddField(
            model_name='jugdments',
            name='label_3',
            field=models.TextField(default='Rendimento interno'),
        ),
        migrations.DeleteModel(
            name='Label_1',
        ),
        migrations.DeleteModel(
            name='Label_2',
        ),
        migrations.DeleteModel(
            name='Label_3',
        ),
    ]
